# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


LiteralString = str
# -- template models.py.jinja --
from pydantic import BaseModel

from . import fields, actions
from ._types import FuncType
from .builder import serialize_base64
from ._compat import PYDANTIC_V2, ConfigDict

if TYPE_CHECKING:
    from .client import Prisma


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class _PrismaModel(BaseModel):
    if PYDANTIC_V2:
        model_config: ClassVar[ConfigDict] = ConfigDict(
            use_enum_values=True,
            arbitrary_types_allowed=True,
            populate_by_name=True,
        )
    elif not TYPE_CHECKING:
        from ._compat import BaseConfig

        class Config(BaseConfig):
            use_enum_values: bool = True
            arbitrary_types_allowed: bool = True
            allow_population_by_field_name: bool = True
            json_encoders: Dict[Any, FuncType] = {
                fields.Base64: serialize_base64,
            }

    # TODO: ensure this is required by subclasses
    __prisma_model__: ClassVar[str]


class BaseUser(_PrismaModel):
    __prisma_model__: ClassVar[Literal['User']] = 'User'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserActions[_PrismaModelT](client or get_client(), cls)


class BaseUserSettings(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UserSettings']] = 'UserSettings'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UserSettingsActions[_PrismaModelT]':
        from .client import get_client

        return actions.UserSettingsActions[_PrismaModelT](client or get_client(), cls)


class BaseSession(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Session']] = 'Session'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SessionActions[_PrismaModelT]':
        from .client import get_client

        return actions.SessionActions[_PrismaModelT](client or get_client(), cls)


class BaseTranscript(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Transcript']] = 'Transcript'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TranscriptActions[_PrismaModelT]':
        from .client import get_client

        return actions.TranscriptActions[_PrismaModelT](client or get_client(), cls)


class BaseTranscriptSegment(_PrismaModel):
    __prisma_model__: ClassVar[Literal['TranscriptSegment']] = 'TranscriptSegment'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TranscriptSegmentActions[_PrismaModelT]':
        from .client import get_client

        return actions.TranscriptSegmentActions[_PrismaModelT](client or get_client(), cls)


class BaseSummary(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Summary']] = 'Summary'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SummaryActions[_PrismaModelT]':
        from .client import get_client

        return actions.SummaryActions[_PrismaModelT](client or get_client(), cls)


class BaseActionItem(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ActionItem']] = 'ActionItem'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ActionItemActions[_PrismaModelT]':
        from .client import get_client

        return actions.ActionItemActions[_PrismaModelT](client or get_client(), cls)


class BaseChatMessage(_PrismaModel):
    __prisma_model__: ClassVar[Literal['ChatMessage']] = 'ChatMessage'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.ChatMessageActions[_PrismaModelT]':
        from .client import get_client

        return actions.ChatMessageActions[_PrismaModelT](client or get_client(), cls)


class BaseEntity(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Entity']] = 'Entity'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EntityActions[_PrismaModelT]':
        from .client import get_client

        return actions.EntityActions[_PrismaModelT](client or get_client(), cls)


class BaseEntityMention(_PrismaModel):
    __prisma_model__: ClassVar[Literal['EntityMention']] = 'EntityMention'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.EntityMentionActions[_PrismaModelT]':
        from .client import get_client

        return actions.EntityMentionActions[_PrismaModelT](client or get_client(), cls)


class BaseTag(_PrismaModel):
    __prisma_model__: ClassVar[Literal['Tag']] = 'Tag'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.TagActions[_PrismaModelT]':
        from .client import get_client

        return actions.TagActions[_PrismaModelT](client or get_client(), cls)


class BaseSessionTag(_PrismaModel):
    __prisma_model__: ClassVar[Literal['SessionTag']] = 'SessionTag'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.SessionTagActions[_PrismaModelT]':
        from .client import get_client

        return actions.SessionTagActions[_PrismaModelT](client or get_client(), cls)


class BaseUsageLog(_PrismaModel):
    __prisma_model__: ClassVar[Literal['UsageLog']] = 'UsageLog'

    @classmethod
    def prisma(cls: Type[_PrismaModelT], client: Optional['Prisma'] = None) -> 'actions.UsageLogActions[_PrismaModelT]':
        from .client import get_client

        return actions.UsageLogActions[_PrismaModelT](client or get_client(), cls)


